//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// FmStation.rc で使用
//
#define IDD_SETTING_TAB                 101
#define IDD_FMSTATION_DIALOG            102
#define IDD_MODULE_TAB                  103
#define IDD_MIDI_TAB                    104
#define IDD_INST_TAB                    105
#define IDD_BATCH_DIALOG                106
#define IDD_TIMBRE_DIALOG               107
#define IDD_INST_TAB2                   108
#define IDD_DRUM_TAB                    109
#define IDR_MAINFRAME                   128
#define IDB_BLACK_OFF                   138
#define IDB_SMALL_BLACK_OFF             138
#define IDB_BLACK_ON                    139
#define IDB_SMALL_BLACK_ON              139
#define IDB_WHITE_OFF_BOTH              144
#define IDB_SMALL_WHITE_OFF_BOTH        144
#define IDB_WHITE_OFF_LEFT              145
#define IDB_SMALL_WHITE_OFF_LEFT        145
#define IDB_WHITE_OFF_RIGHT             146
#define IDB_SMALL_WHITE_OFF_RIGHT       146
#define IDB_WHITE_ON_BOTH               147
#define IDB_SMALL_WHITE_ON_BOTH         147
#define IDB_WHITE_ON_LEFT               148
#define IDB_SMALL_WHITE_ON_LEFT         148
#define IDB_WHITE_ON_RIGHT              149
#define IDB_SMALL_WHITE_ON_RIGHT        149
#define IDB_MEDIUM_BLACK_OFF            150
#define IDB_MEDIUM_BLACK_ON             151
#define IDB_MEDIUM_WHITE_OFF_BOTH       152
#define IDB_MEDIUM_WHITE_OFF_LEFT       153
#define IDB_MEDIUM_WHITE_OFF_RIGHT      154
#define IDB_MEDIUM_WHITE_ON_BOTH        155
#define IDB_MEDIUM_WHITE_ON_LEFT        156
#define IDB_MEDIUM_WHITE_ON_RIGHT       157
#define IDB_BIG_BLACK_OFF               159
#define IDB_BIG_BLACK_ON                160
#define IDB_BIG_WHITE_OFF_BOTH          161
#define IDB_BIG_WHITE_OFF_LEFT          162
#define IDB_BIG_WHITE_OFF_RIGHT         163
#define IDB_BIG_WHITE_ON_BOTH           164
#define IDB_BIG_WHITE_ON_LEFT           165
#define IDB_BIG_WHITE_ON_RIGHT          166
#define IDB_BITMAP_ALG0                 167
#define IDB_BITMAP_ALG1                 168
#define IDB_BITMAP_ALG2                 169
#define IDB_BITMAP_ALG3                 170
#define IDB_BITMAP_ALG4                 171
#define IDB_BITMAP_ALG5                 172
#define IDB_BITMAP_ALG6                 173
#define IDB_BITMAP_ALG7                 174
#define IDB_BIG_BLACK_ON_INVALID        175
#define IDB_BIG_WHITE_ON_BOTH_INVALID   176
#define IDB_BIG_WHITE_ON_LEFT_INVALID   177
#define IDB_BIG_WHITE_ON_RIGHT_INVALID  178
#define IDC_COMBO_DEVICE                1001
#define IDC_MASTER_TAB                  1002
#define IDC_SETTING_COMBO_DEVICE        1003
#define IDC_MODULE_LIST                 1004
#define IDC_MIDI_LIST                   1005
#define IDC_BUTTON_RESET                1006
#define IDC_INST_LIST_PROGRAM           1008
#define IDC_INST_LIST_BATCH             1009
#define IDC_INST_LIST_TIMBRE            1010
#define IDC_INST_BUTTON_PROGRAM_ADD     1011
#define IDC_INST_SPIN_PROGRAM_BANK      1012
#define IDC_INST_SPIN_BATCH_ORDER       1013
#define IDC_INST_SPIN_TIMBRE_ORDER      1014
#define IDC_INST_BUTTON_PROGRAM_REMOVE  1015
#define IDC_INST_BUTTON_BATCH_ADD       1016
#define IDC_INST_BUTTON_BATCH_DELETE    1017
#define IDC_INST_BUTTON_TIMBRE_ADD      1018
#define IDC_BATCHDLG_EDIT_NAME          1018
#define IDC_INST_BUTTON_TIMBRE_DELETE   1019
#define IDC_TIMBREDLG_EDIT_NAME         1019
#define IDC_INST_BUTTON_BATCH_DUP       1020
#define IDC_BATCHDLG_STATIC_KEYBOARD    1020
#define IDC_INST_BUTTON_TIMBRE_DUP      1021
#define IDC_TIMBREDLG_STATIC_KEYBOARD   1021
#define IDC_SETTING_COPY_FORMAT_COMBO   1022
#define IDC_SETTING_SWAP_COPY_FORMAT_CHECK 1023
#define IDC_SETTING_AUTO_COPY_FORMAT_CHECK 1024
#define IDC_TIMBRE_ALG0_STATIC          1025
#define IDC_TIMBRE_EN_STATIC            1026
#define IDC_TIMBRE_FDE_STATIC           1027
#define IDC_TIMBRE_ALG_STATIC           1028
#define IDC_TIMBRE_FB_STATIC            1029
#define IDC_TIMBRE_NUM_STATIC           1030
#define IDC_TIMBRE_KML_STATIC           1031
#define IDC_TIMBRE_KMH_STATIC           1032
#define IDC_TIMBRE_VOID4_STATIC         1033
#define IDC_TIMBRE_KT_STATIC            1034
#define IDC_TIMBRE_FDT_STATIC           1035
#define IDC_TIMBRE_EN1_STATIC           1036
#define IDC_TIMBRE_FDE1_STATIC          1037
#define IDC_TIMBRE_AR1_STATIC           1038
#define IDC_TIMBRE_DR1_STATIC           1039
#define IDC_TIMBRE_SR1_STATIC           1040
#define IDC_TIMBRE_RR1_STATIC           1041
#define IDC_TIMBRE_SL1_STATIC           1042
#define IDC_TIMBRE_TL1_STATIC           1043
#define IDC_TIMBRE_KS1_STATIC           1044
#define IDC_TIMBRE_MT1_STATIC           1045
#define IDC_TIMBRE_DT1_STATIC           1046
#define IDC_TIMBRE_SSG1_STATIC          1047
#define IDC_TIMBRE_SE_FIX1_STATIC       1048
#define IDC_TIMBRE_SE_KT1_STATIC        1049
#define IDC_TIMBRE_SE_FDT1_STATIC       1050
#define IDC_TIMBRE_EN2_STATIC           1051
#define IDC_TIMBRE_FDE2_STATIC          1052
#define IDC_TIMBRE_AR2_STATIC           1053
#define IDC_TIMBRE_DR2_STATIC           1054
#define IDC_TIMBRE_SR2_STATIC           1055
#define IDC_TIMBRE_RR2_STATIC           1056
#define IDC_TIMBRE_SL2_STATIC           1057
#define IDC_TIMBRE_TL2_STATIC           1058
#define IDC_TIMBRE_KS2_STATIC           1059
#define IDC_TIMBRE_MT2_STATIC           1060
#define IDC_TIMBRE_DT2_STATIC           1061
#define IDC_TIMBRE_SSG2_STATIC          1062
#define IDC_TIMBRE_SE_FIX2_STATIC       1063
#define IDC_TIMBRE_SE_KT2_STATIC        1064
#define IDC_TIMBRE_SE_FDT2_STATIC       1065
#define IDC_TIMBRE_EN3_STATIC           1066
#define IDC_TIMBRE_FDE3_STATIC          1067
#define IDC_TIMBRE_AR3_STATIC           1068
#define IDC_TIMBRE_DR3_STATIC           1069
#define IDC_TIMBRE_SR3_STATIC           1070
#define IDC_TIMBRE_RR3_STATIC           1071
#define IDC_TIMBRE_SL3_STATIC           1072
#define IDC_TIMBRE_TL3_STATIC           1073
#define IDC_TIMBRE_KS3_STATIC           1074
#define IDC_TIMBRE_MT3_STATIC           1075
#define IDC_TIMBRE_DT3_STATIC           1076
#define IDC_TIMBRE_SSG3_STATIC          1077
#define IDC_TIMBRE_SE_FIX3_STATIC       1078
#define IDC_TIMBRE_SE_KT3_STATIC        1079
#define IDC_TIMBRE_SE_FDT3_STATIC       1080
#define IDC_TIMBRE_EN4_STATIC           1081
#define IDC_TIMBRE_FDE4_STATIC          1082
#define IDC_TIMBRE_AR4_STATIC           1083
#define IDC_TIMBRE_DR4_STATIC           1084
#define IDC_TIMBRE_SR4_STATIC           1085
#define IDC_TIMBRE_RR4_STATIC           1086
#define IDC_TIMBRE_SL4_STATIC           1087
#define IDC_TIMBRE_TL4_STATIC           1088
#define IDC_TIMBRE_KS4_STATIC           1089
#define IDC_TIMBRE_MT4_STATIC           1090
#define IDC_TIMBRE_DT4_STATIC           1091
#define IDC_TIMBRE_SSG4_STATIC          1092
#define IDC_TIMBRE_SE_FIX4_STATIC       1093
#define IDC_TIMBRE_SE_KT4_STATIC        1094
#define IDC_TIMBRE_SE_FDT4_STATIC       1095
#define IDC_TIMBRE_SE_STATIC            1097
#define IDC_TIMBRE_FIX_STATIC           1102
#define IDC_TIMBRE_ALG1_STATIC          1103
#define IDC_TIMBRE_ALG2_STATIC          1104
#define IDC_TIMBRE_ALG3_STATIC          1105
#define IDC_TIMBRE_ALG4_STATIC          1106
#define IDC_TIMBRE_ALG5_STATIC          1107
#define IDC_TIMBRE_ALG6_STATIC          1108
#define IDC_TIMBRE_ALG7_STATIC          1109
#define IDC_TIMBRE_VOID1_STATIC         1110
#define IDC_TIMBRE_VOID2_STATIC         1111
#define IDC_TIMBRE_VOID3_STATIC         1112
#define IDC_TIMBRE_OP1_STATIC           1113
#define IDC_TIMBRE_OP2_STATIC           1114
#define IDC_TIMBRE_OP3_STATIC           1115
#define IDC_TIMBRE_OP4_STATIC           1116
#define IDC_SETTING_SLTL_LINK           1117
#define IDC_TIMBRE_LOG                  1118
#define IDC_BUTTON_LOAD                 1119
#define IDC_BATCH_LOG                   1120
#define IDC_BUTTON_SAVE                 1121
#define IDC_SETTING_VOLUME_SLIDER       1122
#define IDC_INST_STATIC_TIMBRE          1123
#define IDC_SETTING_CUTOFF_SLIDER       1123
#define IDC_TIMBREDLG_OK                1124
#define IDC_SETTING_RESONANCE_SLIDER    1124
#define IDC_MASTER_STATIC_LOG           1125
#define IDC_SETTING_DC_CUT_RATE_SLIDER  1125
#define IDC_DRUM_LIST_NOTE              1126
#define IDC_SETTING_PREVIEW_SLIDER      1126
#define IDC_DRUM_LIST_BATCH             1127
#define IDC_DRUM_LIST_TIMBRE            1128
#define IDC_SETTING_RESONANCE_SLIDER2   1128
#define IDC_SETTING_TUNING_SLIDER       1128
#define IDC_DRUM_BUTTON_NOTE_ADD        1129
#define IDC_DRUM_SPIN_PROGRAM           1130
#define IDC_DRUM_BUTTON_NOTE_REMOVE     1131
#define IDC_DRUM_SPIN_BATCH_ORDER       1132
#define IDC_DRUM_BUTTON_BATCH_DUP       1133
#define IDC_DRUM_BUTTON_BATCH_ADD       1134
#define IDC_DRUM_BUTTON_BATCH_DELETE    1135
#define IDC_DRUM_SPIN_TIMBRE_ORDER      1136
#define IDC_DRUM_BUTTON_TIMBRE_DUP      1137
#define IDC_DRUM_BUTTON_TIMBRE_ADD      1138
#define IDC_DRUM_BUTTON_TIMBRE_DELETE   1139
#define IDC_DRUM_STATIC_TIMBRE          1140
#define IDC_SETTING_FILTER_COMBO        1143
#define IDC_SETTING_DC_CUT_CHECK        1145
#define IDC_DRUM_EDIT_PROGRAM           1146
#define IDC_INST_SPIN_BANK              1148
#define IDC_INST_EDIT_BANK              1149
#define IDC_SETTING_PORTAMENTO_COMBO    1150
#define IDC_SETTING_TUNING_STATIC       1152

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
